# Módulo 1: Introdução à Lib Numpy

___

# Imports para a Aula

In [1]:
import numpy as np

---

# Solução do Desafio

## Objetivo:

Construir a **saída esperada** usando as **ferramentas** dadas em cada item.

### [ Item A ]

#### Saída Esperada:

In [2]:
np.array([[-1.,  0.,  0., 0.],
          [-1., -1.,  0., 0.],
          [-1., -1., -1., 0.]])

array([[-1.,  0.,  0.,  0.],
       [-1., -1.,  0.,  0.],
       [-1., -1., -1.,  0.]])

#### Ferramentas:

In [3]:
np.ones?

In [4]:
np.tril?

#### Solução:

In [5]:
np.tril(-np.ones((3, 4)))

array([[-1.,  0.,  0.,  0.],
       [-1., -1.,  0.,  0.],
       [-1., -1., -1.,  0.]])

### [ Item B ]

#### Saída Esperada:

In [6]:
np.array([[ 1.,  0.,  0.,  0.,  0.],
          [ 0.,  2.,  0.,  0.,  0.],
          [ 0.,  0.,  3.,  0.,  0.],
          [ 0.,  0.,  0.,  4.,  0.],
          [ 0.,  0.,  0.,  0.,  5.]])

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

#### Ferramentas:

In [7]:
np.eye?

In [8]:
""" Operador *"""
np.multiply?

#### Solução:

In [9]:
np.eye(5) * np.array([1, 2, 3, 4, 5])

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  0.,  0.],
       [ 0.,  0.,  0.,  4.,  0.],
       [ 0.,  0.,  0.,  0.,  5.]])

### [ Item C ]

#### Saída Esperada:

In [10]:
np.array([[ 0.,  1.,  2.,  3.,  4.],
          [-1.,  0.,  1.,  2.,  3.],
          [-2., -1.,  0.,  1.,  2.],
          [-3., -2., -1.,  0.,  1.],
          [-4., -3., -2., -1.,  0.]])

array([[ 0.,  1.,  2.,  3.,  4.],
       [-1.,  0.,  1.,  2.,  3.],
       [-2., -1.,  0.,  1.,  2.],
       [-3., -2., -1.,  0.,  1.],
       [-4., -3., -2., -1.,  0.]])

#### Ferramentas:

In [11]:
np.ones?

In [12]:
""" Operador * """
np.multiply?

In [13]:
""" Operador + """
np.add?

#### Solução:

In [14]:
A = np.ones((5, 1))
B = np.array([[1, 2, 3, 4, 5]])
C = np.array([[1],
              [2],
              [3],
              [4],
              [5]])
A.dot(B) - C

array([[ 0.,  1.,  2.,  3.,  4.],
       [-1.,  0.,  1.,  2.,  3.],
       [-2., -1.,  0.,  1.,  2.],
       [-3., -2., -1.,  0.,  1.],
       [-4., -3., -2., -1.,  0.]])

### [ Item D ]

#### Saída Esperada:

In [15]:
np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
          [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
          [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
          [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
          [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
          [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
          [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
          [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
          [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

#### Ferramentas:

In [16]:
A = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [17]:
np.dot?

In [18]:
np.transpose?

#### Solução:

In [19]:
A.T.dot(A)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 9, 18, 27, 36, 45, 54, 63, 72, 81]])

### [ Item E ]

#### Saída Esperada:

In [20]:
np.array([[-18,   0,  18]])

array([[-18,   0,  18]])

#### Ferramentas:

In [21]:
A = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
B = np.array([[-1, 0, 1]])
C = np.array([[0, 0, 1, 0, 0, 1, 0, 0, 1]])

In [22]:
np.dot?

In [23]:
np.transpose?

#### Solução:

In [24]:
C.dot(A.T.dot(B))

array([[-18,   0,  18]])